### ISSUE TITLE
Corrección en el texto del readme

### ISSUE THREAD

**Issue by emiarias** [felix9941/Front-RollingGYM-G1#181]
**Mejoras en el readme**
Corregir el texto del detalle del readme que dejo adjunto.

**Captura**
![image](https://github.com/felix9941/Front-RollingGYM-G1/assets/18445151/d8a3843d-20f3-42bc-8fd4-f08de82b7b07)

**Comment by felix9941** [comment]
Buenas noches, se acaba de corregir la redacción del README  en función de lo solicitado
