### ISSUE TITLE
Corregir link del repositorio de frontend para que apunten a los endpoint correspondientes del  backend

### ISSUE THREAD

**Issue by emiarias** [felix9941/Front-RollingGYM-G1#182]
**Mejoras en el código**
Algunas funcionalidades en el frontend quedaron apuntando a la dirección `http://localhost:3002/api/...` en lugar del endpoint del backend. Esto sucede por ejemplo al crear un profesor desde la página del administrador, tambien al visualizar el administrador de planes.

**Captura**
![image](https://github.com/felix9941/Front-RollingGYM-G1/assets/18445151/f991941a-6ef1-4d27-990b-ad3c9678361e)
![image](https://github.com/felix9941/Front-RollingGYM-G1/assets/18445151/903e897f-1c72-4c12-9475-7c159652442e)
![image](https://github.com/felix9941/Front-RollingGYM-G1/assets/18445151/c9f5610d-0fcd-46b3-bf2b-44525e1a41b1)

**Comment by felix9941** [comment]
Correcciones de los errores encontrados ya solucionados tanto para Admin Profesores como Admin Planes
