### ISSUE TITLE
Error al crear un nuevo producto

### ISSUE THREAD

**Issue by emiarias** [felix9941/Front-RollingGYM-G1#183]
Proceso
Al ingresar como administrador a la administración de productos

Resultado esperado
Dar de alta un producto desde la opción nuevo producto

Resultado actual
Al cargar los datos del formulario se visualiza un error en la solicitud, dejo adjunto el error

Captura
![image](https://github.com/felix9941/Front-RollingGYM-G1/assets/18445151/6a331972-b9f9-48e8-8125-4478f4103404)

**Comment by felix9941** [comment]
![Captura de pantalla 2024-07-11 205823](https://github.com/user-attachments/assets/4b90d291-26b4-42ba-9388-113d4f680709)
Con respecto a este error con el grupo no lo podemos identificar, probamos con crear un producto en función del botón Nuevo Producto y se lo realiza correctamente como lo indica la imagen que adjunto
